<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web"/>
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization"/>
    <PackageReference Include="TwMerge"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\"/>
    <Folder Include="wwwroot\img\"/>
    <Folder Include="wwwroot\js\"/>
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Components\UI\Sliders\Slider.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sliders\SliderBase.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sliders\SliderRange.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sliders\SliderThumb.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sliders\SliderTrack.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheet.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetClose.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetContent.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetDescription.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetFooter.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetHeader.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetTitle.razor" />
    <UpToDateCheckInput Remove="Components\UI\Sheet\BbSheetTrigger.razor" />
  </ItemGroup>



  <Target Name="Tailwind" BeforeTargets="Build">
    <Exec WorkingDirectory="Client" Command="npm install"
          Condition=" !Exists('Client/node_modules') "
    />
    <Exec Command="npx @tailwindcss/cli -i ./css/styles.css -o ../wwwroot/css/styles.css"
          WorkingDirectory="Client"
    />
  </Target>

  <Target Name="BuildJs" BeforeTargets="Build">
    <!-- Install node_modules if missing -->
    <Exec WorkingDirectory="Client"
          Command="npm install"
          Condition="!Exists('Client/node_modules')"/>

    <!-- Run your esbuild bundler -->
    <Exec WorkingDirectory="Client"
          Command="npm run build:js"/>
  </Target>

</Project>
