version: '3.9'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: heracles
        ports:
            - "5432:5432"
    
    loki:
        image: grafana/loki:latest
        ports:
            - "3100:3100"
    
    grafana:
        image: grafana/grafana:latest
        depends_on:
            - loki
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        ports:
            - "3001:3000"
    
    api:
        image: api
        build:
            context: .
            dockerfile: src/Api/Dockerfile
        
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=80
            
            ## Azure AD Configuration
            - AzureAd__Instance=https://login.microsoftonline.com/
            - AzureAd__Domain=qualified.domain.name
            - AzureAd__TenantId=22222222-2222-2222-2222-222222222222
            - AzureAd__ClientId=11111111-1111-1111-11111111111111111
            - AzureAd__ClientSecret=something~something-else
            - AzureAd_Scope="openid profile api://some-api/default"
            - AzureAd__Read_Role=User
            - AzureAd__Write_Role=Admin
            - AzureAd__CallbackPath=/signin-oidc
            
            ## SQL Server Configuration
            - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=heracles
            ## Serilog Configuration
            - Serilog_MinimumLevel__Default="Warning"
            - Serilog__WriteTo__1__Args__uri=http://loki:3100
            ## CORS Configuration
            - CorsSettings__AllowedOrigins=http://localhost:3000
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - postgres
            - grafana
            - loki


        

      
      

      

  
